name: CI/CD

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push API Docker image
        run: |
          docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/api:latest ./api
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/api:latest

      # - name: Build and push Client Docker image
      #   run: |
      #     docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/client:latest ./client
      #     docker push ${{ secrets.DOCKERHUB_USERNAME }}/client:latest

      # - name: Build and push Server Docker image
      #   run: |
      #     docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/server:latest ./server
      #     docker push ${{ secrets.DOCKERHUB_USERNAME }}/server:latest
